//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedarikZinciriOtomasyonu.VarlikKatmani
{
    using System;
    using System.Collections.Generic;
    
    public partial class firma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public firma()
        {
            this.firmapersonel = new HashSet<firmapersonel>();
            this.talep = new HashSet<talep>();
            this.uretimtesisi = new HashSet<uretimtesisi>();
        }
    
        public int FirmaID { get; set; }
        public string FirmaAdi { get; set; }
        public string FirmaAciklama { get; set; }
        public string Telefon { get; set; }
        public string Fax { get; set; }
        public string EPosta { get; set; }
		//public Nullable<bool> Etkin { get; set; }
		public bool Etkin { get; set; }
		public Nullable<int> AdresID { get; set; }
        public string FirmaTipi { get; set; }
    
        public virtual adres adres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<firmapersonel> firmapersonel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<talep> talep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uretimtesisi> uretimtesisi { get; set; }
    }
}
