//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedarikZinciriOtomasyonu.VarlikKatmani
{
	using System;
	using System.Collections.Generic;

	public partial class kisi
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public kisi()
		{
			this.firmapersonel = new HashSet<firmapersonel>();
			this.kisisifre = new HashSet<kisisifre>();
			this.tedarik = new HashSet<tedarik>();
		}

		public int KisiID { get; set; }
		public string TCKNO { get; set; }
		public int YetkiID { get; set; }
		public string Ad { get; set; }
		public string Soyad { get; set; }
		public string EPosta { get; set; }
		public string Telefon { get; set; }
		//public Nullable<bool> Etkin { get; set; }
		public bool Etkin { get; set; }
		public string Guid { get; set; }

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<firmapersonel> firmapersonel { get; set; }
		public virtual yetki yetki { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<kisisifre> kisisifre { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<tedarik> tedarik { get; set; }
	}
}
