//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedarikZinciriOtomasyonu.VarlikKatmani
{
    using System;
    using System.Collections.Generic;
    
    public partial class kisisifre
    {
        public int KisiSifreID { get; set; }
        public Nullable<int> KisiID { get; set; }
        public string Sifre { get; set; }
    
        public virtual kisi kisi { get; set; }
    }
}
