//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedarikZinciriOtomasyonu.VarlikKatmani
{
    using System;
    using System.Collections.Generic;
    
    public partial class talep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public talep()
        {
            this.tedarik = new HashSet<tedarik>();
        }
    
        public int TalepID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> FirmaID { get; set; }
        public Nullable<float> TalepMiktari { get; set; }
        public Nullable<System.DateTime> TalepTarihi { get; set; }
    
        public virtual firma firma { get; set; }
        public virtual urun urun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tedarik> tedarik { get; set; }
    }
}
