//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedarikZinciriOtomasyonu.VarlikKatmani
{
    using System;
    using System.Collections.Generic;
    
    public partial class tedarik
    {
        public int TedarikID { get; set; }
        public Nullable<int> KisiID { get; set; }
        public Nullable<int> TalepID { get; set; }
        public Nullable<int> TeslimAdresiID { get; set; }
        public Nullable<int> CikisAdresiID { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public string Durum { get; set; }
        public Nullable<float> TedarikUcreti { get; set; }
    
        public virtual adres adres { get; set; }
        public virtual adres adres1 { get; set; }
        public virtual kisi kisi { get; set; }
        public virtual talep talep { get; set; }
    }
}
