//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedarikZinciriOtomasyonu.VarlikKatmani
{
    using System;
    using System.Collections.Generic;
    
    public partial class uretimtesisi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uretimtesisi()
        {
            this.urun = new HashSet<urun>();
        }
    
        public int UretimTesisiID { get; set; }
        public int TesisKategoriID { get; set; }
        public int AdresID { get; set; }
        public int FirmaID { get; set; }
        public string TesisAdi { get; set; }
        public string TesisAciklama { get; set; }
        public Nullable<float> UretimKapasitesi { get; set; }
    
        public virtual adres adres { get; set; }
        public virtual firma firma { get; set; }
        public virtual tesiskategori tesiskategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<urun> urun { get; set; }
    }
}
