//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TedarikZinciriOtomasyonu.VarlikKatmani
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunkategori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public urunkategori()
        {
            this.urun = new HashSet<urun>();
        }
    
        public int UrunKategoriID { get; set; }
        public string UrunKategoriAdi { get; set; }
        public string UrunKategoriAciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<urun> urun { get; set; }
    }
}
